/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

/**
 *
 * @author User
 */
import Admin.Adminpanel;
import dbconnect.DatabaseHelper;
import java.sql.*;
import javax.swing.JOptionPane;
import myproject.Home;

public class Mainlog extends javax.swing.JFrame {

    /**
     * Creates new form Mainlog
     */
    Connection con = null;
    PreparedStatement pst = null;
    Statement stmt = null;
    ResultSet rs = null;

    public Mainlog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        che = new javax.swing.JComboBox();
        Login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Username:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 198, 70, -1));

        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });
        jPanel1.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 185, 150, 30));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 263, 70, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 150, 30));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Select Department:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 322, 130, -1));

        che.setFont(new java.awt.Font("Monotype Corsiva", 3, 14)); // NOI18N
        che.setForeground(new java.awt.Color(0, 51, 51));
        che.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----Department-----", "      Admin", "      Reception" }));
        jPanel1.add(che, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 309, 150, 30));

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 350, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/log.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 660, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String N;
        char[] P;
        String ch;
        ch = che.getSelectedItem().toString();
        N = uid.getText();
        P = pass.getPassword();
        int count = 0;
        String pa = String.valueOf(P);//convert char array to string
        if (!N.isEmpty()) {
            if (!pa.isEmpty()) {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DatabaseHelper.getDBConnection();
                    ResultSet rs = null;
                    Statement st;
                    st = con.createStatement();

                    if (che.getSelectedIndex() == 0) {
                        //                        rs = st.executeQuery("select * from admin_info where admin_user='" + N + "' and admin_pass= '" + pa + "'");

                    } else {
                        if (che.getSelectedIndex() == 1) {
                            rs = st.executeQuery("select * from admin where admin_user='" + N + "' and admin_pass= '" + pa + "'");

                        } else {
                            if (che.getSelectedIndex() == 2) {
                                rs = st.executeQuery("select * from reception_panel where user_id='" + N + "' and pass= '" + pa + "'");

                            }
                        }
                    }

                    while (rs.next()) {
                        count = rs.getRow();
                        System.out.println(" done ");
                    }

                    if (count > 0) {
                        if (che.getSelectedIndex() == 0) {

                        } else {
                            if (che.getSelectedIndex() == 1) {
                                //String userid=uid.getText();
                                Adminpanel stu = new Adminpanel();
                                //stu.admin.setText(N);
                                this.dispose();
                                stu.setVisible(true);

                            } else {
                                if (che.getSelectedIndex() == 2) {
                                    Home stu = new Home();
                                    //stu.uname.setText(N);
                                    //stu.upic.setIcon(aktar.png);
                                    this.dispose();
                                    stu.setVisible(true);
                                }
                            }
                        }

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Login Faild");

                    }
                    rs.close();
                    st.close();
                    con.close();

                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please enter your password ");
                pass.requestFocus();

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Enter your user id ");
            uid.requestFocus();
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainlog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JComboBox che;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
